# Travis Continuos Integration
# Currently only tests notebook files
# Based on https://conda.pydata.org/docs/travis.html
dist: xenial
language: python

notifications:
  email: false

jobs:
  include:
    - env: NAME="Latest Everything."
      python: 3.9
    - env: NAME="Oldest Version."
      python: 3.6

before_install:
  - |
        MODIFIED_FILES=$(git diff --name-only "$TRAVIS_COMMIT_RANGE" 2>/dev/null)
        if [ $? -eq 0 ] && ! echo "$MODIFIED_FILES" | grep -qvE '(.md)|(.rst)|(.html)|(.png)|(.ico)'
          then
          echo "Only doc files were updated, not running the CI."
          exit
        fi
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
  - conda update -q conda
  - conda info -a

install:
  - conda env create --file ci/environment.yml
  - source activate proplot-dev
  - conda list
  - which conda
  - which python
  - python setup.py sdist bdist_wheel
  - pip install --user ./dist/*.whl

script:
  - ci/run-linter.sh
